import Head from 'next/head'
import styles from '../../styles/Portfolio.module.scss'
import  { motion } from 'framer-motion';

export const PROJECT_ONE = [
  { 
    name: "Project One",
    addition: "Hubblee Lighting",
    thumb: '/assets/_thumbs/project-one-thumb.jpg',
    id: 'project-one'
  }, 
];


const transition = { duration: 1.4, ease: [0.6, 0.01, -0.05, 0.9] };

const ProjectOne = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {PROJECT_ONE.map(p => (
       <motion.div className={styles['portfolio-item']} layoutId={p.id}>
          <div className={styles['portfolio-item--hero']} style={{backgroundImage: `url(${p.thumb})`}}>
            <div className="container">
              <motion.h2 initial={{ opacity: 0, y: 50 }}
              animate={{
                opacity: 1,
                y: 0,
                transition: { delay: .3, ...transition },
              }} className={styles['portfolio-item--title']}>{p.name}</motion.h2> 
            </div>
          </div>
        </motion.div>
      ))}

      <footer className={styles.footer}>
       
      </footer>
    </>
  )
}

export default ProjectOne
