import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import { motion } from 'framer-motion'

const PORTFOLIO = [
  { 
    name: "Project One",
    addition: "Hubblee Lighting",
    thumb: '/assets/_thumbs/project-one-thumb.jpg',
    link: '/portfolio/project-one',
    id: 'project-one'
  }, 
  { 
    name: "Project Two",
    thumb: '/assets/_thumbs/project-one-thumb.jpg',
  }
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h1 style={{marginTop: 96}}>Hey, I'm Jeremy — <br/>Industrial &amp; Product Designer.</h1>
        <div className={styles['portfolio']}>
          {PORTFOLIO.map(p => (
            <motion.div className={styles['portfolio-item']} layoutId={p.id} whileHover={{ scale: 1.01 }}>
              <Link href={`${p.link}`}>
                <div className={styles['portfolio-item--hero']} style={{backgroundImage: `url(${p.thumb})`}}/>
              </Link>
              <h2>{p.name}</h2> 
              {p.addition && <p>{p.addition}</p>}
            </motion.div>
          ))}
        </div>
      </div>

      <footer className={styles.footer}>
       
      </footer>
    </>
  )
}

export default Home
